var myNum;
var myBoolean;
var myString;
var strNumTuple;
var strArr;
var boolArr;
var numArr;
myString = "hello world".slice(0, 3);
myNum = 5;
myBoolean = true;
strArr = ["Hello", "Bhuvanesh", "Anji", "Raju", "Vijay"];
numArr = [1, 5, 4, 7, 8, 10, 20];
boolArr = [true, false, true, false, false];
strNumTuple = ['Bhuvanesh', 1];
console.log(myString);
